/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_audumla_perio_rpi_jni_RPiPlatformNative */

#ifndef _Included_net_audumla_perio_rpi_jni_RPiPlatformNative
#define _Included_net_audumla_perio_rpi_jni_RPiPlatformNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_audumla_perio_rpi_jni_RPiPlatformNative
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_rpi_jni_RPiPlatformNative_init
  (JNIEnv *, jclass);

/*
 * Class:     net_audumla_perio_rpi_jni_RPiPlatformNative
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_audumla_perio_rpi_jni_RPiPlatformNative_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     net_audumla_perio_rpi_jni_RPiPlatformNative
 * Method:    getRevision
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_rpi_jni_RPiPlatformNative_getRevision
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
