/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_audumla_perio_i2c_rpi_jni_RPiI2CNative */

#ifndef _Included_net_audumla_perio_i2c_rpi_jni_RPiI2CNative
#define _Included_net_audumla_perio_i2c_rpi_jni_RPiI2CNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    open
 * Signature: (IILnet/audumla/perio/jni/ErrorHandler;)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_open
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    close
 * Signature: (ILnet/audumla/perio/jni/ErrorHandler;)V
 */
JNIEXPORT void JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_close
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    setClock
 * Signature: (IILnet/audumla/perio/jni/ErrorHandler;)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_setClock
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    getClock
 * Signature: (ILnet/audumla/perio/jni/ErrorHandler;)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_getClock
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    write
 * Signature: (IIBBBLnet/audumla/perio/jni/ErrorHandler;)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_write__IIBBBLnet_audumla_perio_jni_ErrorHandler_2
  (JNIEnv *, jclass, jint, jint, jbyte, jbyte, jbyte, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    read
 * Signature: (IIBLnet/audumla/perio/jni/ErrorHandler;)B
 */
JNIEXPORT jbyte JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_read__IIBLnet_audumla_perio_jni_ErrorHandler_2
  (JNIEnv *, jclass, jint, jint, jbyte, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    write
 * Signature: (IIBBLnet/audumla/perio/jni/ErrorHandler;)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_write__IIBBLnet_audumla_perio_jni_ErrorHandler_2
  (JNIEnv *, jclass, jint, jint, jbyte, jbyte, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    read
 * Signature: (IILnet/audumla/perio/jni/ErrorHandler;)B
 */
JNIEXPORT jbyte JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_read__IILnet_audumla_perio_jni_ErrorHandler_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    write
 * Signature: (IIII[BBLnet/audumla/perio/jni/ErrorHandler;)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_write__IIII_3BBLnet_audumla_perio_jni_ErrorHandler_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray, jbyte, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    write
 * Signature: (IIBIII[B[BLnet/audumla/perio/jni/ErrorHandler;)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_write__IIBIII_3B_3BLnet_audumla_perio_jni_ErrorHandler_2
  (JNIEnv *, jclass, jint, jint, jbyte, jint, jint, jint, jbyteArray, jbyteArray, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    read
 * Signature: (IIII[BBLnet/audumla/perio/jni/ErrorHandler;)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_read__IIII_3BBLnet_audumla_perio_jni_ErrorHandler_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray, jbyte, jobject);

/*
 * Class:     net_audumla_perio_i2c_rpi_jni_RPiI2CNative
 * Method:    read
 * Signature: (IIBIII[B[BLnet/audumla/perio/jni/ErrorHandler;)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_perio_i2c_rpi_jni_RPiI2CNative_read__IIBIII_3B_3BLnet_audumla_perio_jni_ErrorHandler_2
  (JNIEnv *, jclass, jint, jint, jbyte, jint, jint, jint, jbyteArray, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
