/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative */

#ifndef _Included_net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative
#define _Included_net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative
 * Method:    write
 * Signature: (III[BB)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative_write__III_3BB
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jbyte);

/*
 * Class:     net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative
 * Method:    write
 * Signature: (IIIII[B[B)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative_write__IIIII_3B_3B
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative
 * Method:    read
 * Signature: (III[BB)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative_read__III_3BB
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jbyte);

/*
 * Class:     net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative
 * Method:    read
 * Signature: (IIIII[B[B)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_deviceaccess_i2cbus_rpi_jni_RPiI2CNative_read__IIIII_3B_3B
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
