/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_audumla_devices_io_i2c_jni_rpi_I2C */

#ifndef _Included_net_audumla_devices_io_i2c_jni_rpi_I2C
#define _Included_net_audumla_devices_io_i2c_jni_rpi_I2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeByteDirect
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeByteDirect
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeBytesDirect
 * Signature: (III[B)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeBytesDirect
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeByte
 * Signature: (IIB)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeByte
  (JNIEnv *, jclass, jint, jint, jbyte);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeWord
 * Signature: (IIC)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeWord
  (JNIEnv *, jclass, jint, jint, jchar);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeBytes
 * Signature: (IIII[B)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeBytes
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeWords
 * Signature: (IIII[C)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeWords
  (JNIEnv *, jclass, jint, jint, jint, jint, jcharArray);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    readByteDirect
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_readByteDirect
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    readByte
 * Signature: (II)B
 */
JNIEXPORT jbyte JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_readByte
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    readWord
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_readWord
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeByteDirectMask
 * Signature: (IBB)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeByteDirectMask
  (JNIEnv *, jclass, jint, jbyte, jbyte);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeBytesDirectMask
 * Signature: (III[BB)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeBytesDirectMask
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jbyte);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeByteMask
 * Signature: (IIBB)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeByteMask
  (JNIEnv *, jclass, jint, jint, jbyte, jbyte);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeBytesMask
 * Signature: (IIII[BB)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeBytesMask
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray, jbyte);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeWordMask
 * Signature: (IICC)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeWordMask
  (JNIEnv *, jclass, jint, jint, jchar, jchar);

/*
 * Class:     net_audumla_devices_io_i2c_jni_rpi_I2C
 * Method:    writeWordsMask
 * Signature: (IIII[CC)I
 */
JNIEXPORT jint JNICALL Java_net_audumla_devices_io_i2c_jni_rpi_I2C_writeWordsMask
  (JNIEnv *, jclass, jint, jint, jint, jint, jcharArray, jchar);

#ifdef __cplusplus
}
#endif
#endif
